spring.application.name=MiniCart

spring.datasource.url=jdbc:mysql://localhost:3306/minicart
spring.datasource.username=minicartuser
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Run data.sql after Hibernate has created/updated tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always